FROM python:3.7.3-slim-stretch

RUN apt-get update && apt-get install ca-certificates build-essentials

WORKDIR /usr/src/app
COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY pcAgent.py .
COPY pc.properties .

CMD [ "python", "./pcAgent.py" ]
