FROM python:3.7.3-slim-stretch

RUN apt-get update && apt-get install -y ca-certificates build-essential

WORKDIR /usr/src/app
COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY c8yMQTT.py .
COPY pcAgent.py .

CMD [ "python", "./pcAgent.py" ]